name: Automatyczne testy Pythona

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod repo
        uses: actions/checkout@v4

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zainstaluj zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Uruchom testy
        run: pytest
