name: Testy Pythona

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Ustaw Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zainstaluj zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Uruchom pytest
        run: pytest
