name: Zapytanie z sekretem

on: [push]

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - name: Wykonaj zapytanie HTTP z tokenem
        run: |
          echo "Wysyłam zapytanie HTTP z sekretem:"
          curl -H "Authorization: Bearer ${{ secrets.MY_SECRET }}" https://httpbin.org/get
